### ISSUE TITLE
[question/help]: 运行checkin脚本报错 An `executablePath` or `channel` must be specified for `puppeteer-core`

### ISSUE THREAD

**Issue by ybbbi** [DullSword/GLaDOS-CheckIn#56]
### 问题

Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
[33](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:34)
    at assert (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
[34](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:35)
    at ChromeLauncher.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:69:36)
[35](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:36)
    at PuppeteerNode.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:146:105)
[36](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:37)
    at PuppeteerExtra.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-extra/dist/index.cjs.js:128:41)
[37](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:38)
    at async checkInAndGetStatus (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/checkin.js:58:21)
[38](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:39)
    at async Promise.all (index 0)
[39](https://github.com/DullSword/GLaDOS-CheckIn/actions/runs/3301037802/jobs/5446116352#step:6:40)
    at async GLaDOSCheckIn (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/checkin.js:175:27)

**Comment by ybbbi** [comment]
将 配置文件 checkin.yaml 中 puppeteer版本改为17.1.3即可
run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
run: npm install puppeteer@17.1.3 puppeteer-extra puppeteer-extra-plugin-stealth

**Comment by DullSword** [comment]
看来你已经自己解决了，其实锁定到上个版本就可以。
