### ISSUE TITLE
[Bug]: action 签到失败

### ISSUE THREAD

**Issue by SplitGemini** [DullSword/GLaDOS-CheckIn#59]
### 分支

main

### 当前行为

Run node checkin.js
Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at ChromeLauncher.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:69:36)
    at PuppeteerNode.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:146:105)
    at PuppeteerExtra.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-extra/dist/index.cjs.js:128:41)
    at async checkInAndGetStatus (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/checkin.js:58:21)
    at async Promise.all (index 0)
    at async GLaDOSCheckIn (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/checkin.js:1[7](https://github.com/SplitGemini/GLaDOS-CheckIn/actions/runs/3301794478/jobs/5447727371#step:6:8)5:27)

### 预期行为

应该成功

### 工作流日志

2022-10-22T03:37:02.1390700Z Requested labels: ubuntu-latest
2022-10-22T03:37:02.1390735Z Job defined at: SplitGemini/GLaDOS-CheckIn/.github/workflows/checkin.yml@refs/heads/main
2022-10-22T03:37:02.1390751Z Waiting for a runner to pick up this job...
2022-10-22T03:37:02.3912969Z Job is waiting for a hosted runner to come online.
2022-10-22T03:37:07.1202137Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2022-10-22T03:37:09.6560532Z Current runner version: '2.298.2'
2022-10-22T03:37:09.6592375Z ##[group]Operating System
2022-10-22T03:37:09.6593055Z Ubuntu
2022-10-22T03:37:09.6593567Z 20.04.5
2022-10-22T03:37:09.6593936Z LTS
2022-10-22T03:37:09.6594328Z ##[endgroup]
2022-10-22T03:37:09.6594691Z ##[group]Runner Image
2022-10-22T03:37:09.6595184Z Image: ubuntu-20.04
2022-10-22T03:37:09.6595637Z Version: 20221018.2
2022-10-22T03:37:09.6596318Z Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20221018.2/images/linux/Ubuntu2004-Readme.md
2022-10-22T03:37:09.6597166Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20221018.2
2022-10-22T03:37:09.6597827Z ##[endgroup]
2022-10-22T03:37:09.6598230Z ##[group]Runner Image Provisioner
2022-10-22T03:37:09.6598671Z 2.0.91.1
2022-10-22T03:37:09.6599071Z ##[endgroup]
2022-10-22T03:37:09.6600415Z ##[group]GITHUB_TOKEN Permissions
2022-10-22T03:37:09.6601249Z Actions: write
2022-10-22T03:37:09.6601664Z Checks: write
2022-10-22T03:37:09.6602261Z Contents: write
2022-10-22T03:37:09.6602760Z Deployments: write
2022-10-22T03:37:09.6603203Z Discussions: write
2022-10-22T03:37:09.6603622Z Issues: write
2022-10-22T03:37:09.6604040Z Metadata: read
2022-10-22T03:37:09.6604574Z Packages: write
2022-10-22T03:37:09.6604912Z Pages: write
2022-10-22T03:37:09.6605304Z PullRequests: write
2022-10-22T03:37:09.6605750Z RepositoryProjects: write
2022-10-22T03:37:09.6606245Z SecurityEvents: write
2022-10-22T03:37:09.6606650Z Statuses: write
2022-10-22T03:37:09.6607034Z ##[endgroup]
2022-10-22T03:37:09.6611025Z Secret source: Actions
2022-10-22T03:37:09.6611630Z Prepare workflow directory
2022-10-22T03:37:09.7577981Z Prepare all required actions
2022-10-22T03:37:09.7792877Z Getting action download info
2022-10-22T03:37:10.0335488Z Download action repository 'actions/checkout@v2' (SHA:e2f20e631ae6d7dd3b768f56a5d2af784dd54791)
2022-10-22T03:37:10.7714146Z Download action repository 'actions/setup-node@v1' (SHA:f1f314fca9dfce2769ece7d933488f076716723e)
2022-10-22T03:37:11.3108236Z Download action repository 'gautamkrishnar/keepalive-workflow@master' (SHA:1b33e4ef553c59eef0e3450666408021f4b0f456)
2022-10-22T03:37:11.8356370Z Download action repository 'Mattraks/delete-workflow-runs@v2' (SHA:5ebc537fc6b4f5c1634865f0030271fb6776b28d)
2022-10-22T03:37:12.8218482Z ##[group]Run actions/checkout@v2
2022-10-22T03:37:12.8218849Z with:
2022-10-22T03:37:12.8219152Z   repository: SplitGemini/GLaDOS-CheckIn
2022-10-22T03:37:12.8219768Z   token: ***
2022-10-22T03:37:12.8220031Z   ssh-strict: true
2022-10-22T03:37:12.8220322Z   persist-credentials: true
2022-10-22T03:37:12.8220593Z   clean: true
2022-10-22T03:37:12.8220844Z   fetch-depth: 1
2022-10-22T03:37:12.8221095Z   lfs: false
2022-10-22T03:37:12.8221345Z   submodules: false
2022-10-22T03:37:12.8221631Z   set-safe-directory: true
2022-10-22T03:37:12.8221997Z ##[endgroup]
2022-10-22T03:37:13.2204006Z Syncing repository: SplitGemini/GLaDOS-CheckIn
2022-10-22T03:37:13.2207015Z ##[group]Getting Git version info
2022-10-22T03:37:13.2208247Z Working directory is '/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn'
2022-10-22T03:37:13.2209765Z [command]/usr/bin/git version
2022-10-22T03:37:13.2391677Z git version 2.38.1
2022-10-22T03:37:13.2403209Z ##[endgroup]
2022-10-22T03:37:13.2427535Z Temporarily overriding HOME='/home/runner/work/_temp/5fcd134a-d63f-43b6-8f0f-690eaa09091a' before making global git config changes
2022-10-22T03:37:13.2430079Z Adding repository directory to the temporary git global config as a safe directory
2022-10-22T03:37:13.2437439Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn
2022-10-22T03:37:13.2500063Z Deleting the contents of '/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn'
2022-10-22T03:37:13.2508198Z ##[group]Initializing the repository
2022-10-22T03:37:13.2515308Z [command]/usr/bin/git init /home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn
2022-10-22T03:37:13.2658790Z hint: Using 'master' as the name for the initial branch. This default branch name
2022-10-22T03:37:13.2659651Z hint: is subject to change. To configure the initial branch name to use in all
2022-10-22T03:37:13.2660404Z hint: of your new repositories, which will suppress this warning, call:
2022-10-22T03:37:13.2660852Z hint: 
2022-10-22T03:37:13.2661367Z hint: 	git config --global init.defaultBranch <name>
2022-10-22T03:37:13.2661671Z hint: 
2022-10-22T03:37:13.2662120Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2022-10-22T03:37:13.2662795Z hint: 'development'. The just-created branch can be renamed via this command:
2022-10-22T03:37:13.2663443Z hint: 
2022-10-22T03:37:13.2663869Z hint: 	git branch -m <name>
2022-10-22T03:37:13.2669640Z Initialized empty Git repository in /home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/.git/
2022-10-22T03:37:13.2682515Z [command]/usr/bin/git remote add origin https://github.com/SplitGemini/GLaDOS-CheckIn
2022-10-22T03:37:13.2742203Z ##[endgroup]
2022-10-22T03:37:13.2743136Z ##[group]Disabling automatic garbage collection
2022-10-22T03:37:13.2747425Z [command]/usr/bin/git config --local gc.auto 0
2022-10-22T03:37:13.2782801Z ##[endgroup]
2022-10-22T03:37:13.2783674Z ##[group]Setting up auth
2022-10-22T03:37:13.2792451Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-10-22T03:37:13.2832728Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-10-22T03:37:13.3379600Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-10-22T03:37:13.3421166Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-10-22T03:37:13.3692300Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2022-10-22T03:37:13.3737730Z ##[endgroup]
2022-10-22T03:37:13.3738802Z ##[group]Fetching the repository
2022-10-22T03:37:13.3749206Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +7ac86cb2b2dacd968391555db303b6ef6aa525a2:refs/remotes/origin/main
2022-10-22T03:37:13.7885973Z remote: Enumerating objects: 33, done.        
2022-10-22T03:37:13.7889829Z remote: Counting objects:   3% (1/33)        
2022-10-22T03:37:13.7890897Z remote: Counting objects:   6% (2/33)        
2022-10-22T03:37:13.7891954Z remote: Counting objects:   9% (3/33)        
2022-10-22T03:37:13.7893234Z remote: Counting objects:  12% (4/33)        
2022-10-22T03:37:13.7895116Z remote: Counting objects:  15% (5/33)        
2022-10-22T03:37:13.7895625Z remote: Counting objects:  18% (6/33)        
2022-10-22T03:37:13.7896206Z remote: Counting objects:  21% (7/33)        
2022-10-22T03:37:13.7896818Z remote: Counting objects:  24% (8/33)        
2022-10-22T03:37:13.7897405Z remote: Counting objects:  27% (9/33)        
2022-10-22T03:37:13.7898012Z remote: Counting objects:  30% (10/33)        
2022-10-22T03:37:13.7898606Z remote: Counting objects:  33% (11/33)        
2022-10-22T03:37:13.7899107Z remote: Counting objects:  36% (12/33)        
2022-10-22T03:37:13.7899666Z remote: Counting objects:  39% (13/33)        
2022-10-22T03:37:13.7900094Z remote: Counting objects:  42% (14/33)        
2022-10-22T03:37:13.7900665Z remote: Counting objects:  45% (15/33)        
2022-10-22T03:37:13.7901167Z remote: Counting objects:  48% (16/33)        
2022-10-22T03:37:13.7901690Z remote: Counting objects:  51% (17/33)        
2022-10-22T03:37:13.7902191Z remote: Counting objects:  54% (18/33)        
2022-10-22T03:37:13.7902717Z remote: Counting objects:  57% (19/33)        
2022-10-22T03:37:13.7903240Z remote: Counting objects:  60% (20/33)        
2022-10-22T03:37:13.7903763Z remote: Counting objects:  63% (21/33)        
2022-10-22T03:37:13.7904270Z remote: Counting objects:  66% (22/33)        
2022-10-22T03:37:13.7904806Z remote: Counting objects:  69% (23/33)        
2022-10-22T03:37:13.7905889Z remote: Counting objects:  72% (24/33)        
2022-10-22T03:37:13.7906339Z remote: Counting objects:  75% (25/33)        
2022-10-22T03:37:13.7906776Z remote: Counting objects:  78% (26/33)        
2022-10-22T03:37:13.7907221Z remote: Counting objects:  81% (27/33)        
2022-10-22T03:37:13.7908340Z remote: Counting objects:  84% (28/33)        
2022-10-22T03:37:13.7908977Z remote: Counting objects:  87% (29/33)        
2022-10-22T03:37:13.7909535Z remote: Counting objects:  90% (30/33)        
2022-10-22T03:37:13.7909982Z remote: Counting objects:  93% (31/33)        
2022-10-22T03:37:13.7910475Z remote: Counting objects:  96% (32/33)        
2022-10-22T03:37:13.7910988Z remote: Counting objects: 100% (33/33)        
2022-10-22T03:37:13.7911415Z remote: Counting objects: 100% (33/33), done.        
2022-10-22T03:37:13.7912097Z remote: Compressing objects:   3% (1/32)        
2022-10-22T03:37:13.7912687Z remote: Compressing objects:   6% (2/32)        
2022-10-22T03:37:13.7914084Z remote: Compressing objects:   9% (3/32)        
2022-10-22T03:37:13.7914717Z remote: Compressing objects:  12% (4/32)        
2022-10-22T03:37:13.7915212Z remote: Compressing objects:  15% (5/32)        
2022-10-22T03:37:13.7915716Z remote: Compressing objects:  18% (6/32)        
2022-10-22T03:37:13.7916139Z remote: Compressing objects:  21% (7/32)        
2022-10-22T03:37:13.7916654Z remote: Compressing objects:  25% (8/32)        
2022-10-22T03:37:13.7917076Z remote: Compressing objects:  28% (9/32)        
2022-10-22T03:37:13.7917557Z remote: Compressing objects:  31% (10/32)        
2022-10-22T03:37:13.7917985Z remote: Compressing objects:  34% (11/32)        
2022-10-22T03:37:13.7918496Z remote: Compressing objects:  37% (12/32)        
2022-10-22T03:37:13.7918915Z remote: Compressing objects:  40% (13/32)        
2022-10-22T03:37:13.7919392Z remote: Compressing objects:  43% (14/32)        
2022-10-22T03:37:13.7919805Z remote: Compressing objects:  46% (15/32)        
2022-10-22T03:37:13.7920280Z remote: Compressing objects:  50% (16/32)        
2022-10-22T03:37:13.7920940Z remote: Compressing objects:  53% (17/32)        
2022-10-22T03:37:13.7921577Z remote: Compressing objects:  56% (18/32)        
2022-10-22T03:37:13.7922178Z remote: Compressing objects:  59% (19/32)        
2022-10-22T03:37:13.7922609Z remote: Compressing objects:  62% (20/32)        
2022-10-22T03:37:13.7923022Z remote: Compressing objects:  65% (21/32)        
2022-10-22T03:37:13.7923438Z remote: Compressing objects:  68% (22/32)        
2022-10-22T03:37:13.7923863Z remote: Compressing objects:  71% (23/32)        
2022-10-22T03:37:13.7924279Z remote: Compressing objects:  75% (24/32)        
2022-10-22T03:37:13.7924742Z remote: Compressing objects:  78% (25/32)        
2022-10-22T03:37:13.7925196Z remote: Compressing objects:  81% (26/32)        
2022-10-22T03:37:13.7925731Z remote: Compressing objects:  84% (27/32)        
2022-10-22T03:37:13.7926202Z remote: Compressing objects:  87% (28/32)        
2022-10-22T03:37:13.7926870Z remote: Compressing objects:  90% (29/32)        
2022-10-22T03:37:13.7927377Z remote: Compressing objects:  93% (30/32)        
2022-10-22T03:37:13.7928001Z remote: Compressing objects:  96% (31/32)        
2022-10-22T03:37:13.7928453Z remote: Compressing objects: 100% (32/32)        
2022-10-22T03:37:13.7928904Z remote: Compressing objects: 100% (32/32), done.        
2022-10-22T03:37:14.0341625Z remote: Total 33 (delta 0), reused 28 (delta 0), pack-reused 0        
2022-10-22T03:37:14.0481537Z From https://github.com/SplitGemini/GLaDOS-CheckIn
2022-10-22T03:37:14.0482464Z  * [new ref]         7ac86cb2b2dacd968391555db303b6ef6aa525a2 -> origin/main
2022-10-22T03:37:14.0511986Z ##[endgroup]
2022-10-22T03:37:14.0513892Z ##[group]Determining the checkout info
2022-10-22T03:37:14.0515199Z ##[endgroup]
2022-10-22T03:37:14.0516038Z ##[group]Checking out the ref
2022-10-22T03:37:14.0520740Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2022-10-22T03:37:14.0631135Z Switched to a new branch 'main'
2022-10-22T03:37:14.0636689Z branch 'main' set up to track 'origin/main'.
2022-10-22T03:37:14.0639788Z ##[endgroup]
2022-10-22T03:37:14.0688187Z [command]/usr/bin/git log -1 --format='%H'
2022-10-22T03:37:14.0721951Z '7ac86cb2b2dacd968391555db303b6ef6aa525a2'
2022-10-22T03:37:14.1083779Z ##[group]Run actions/setup-node@v1
2022-10-22T03:37:14.1084074Z with:
2022-10-22T03:37:14.1084307Z   node-version: 14.x
2022-10-22T03:37:14.1084584Z   always-auth: false
2022-10-22T03:37:14.1084846Z ##[endgroup]
2022-10-22T03:37:14.2153287Z [command]/opt/hostedtoolcache/node/14.20.1/x64/bin/node --version
2022-10-22T03:37:14.3276037Z v14.20.1
2022-10-22T03:37:14.3309155Z [command]/opt/hostedtoolcache/node/14.20.1/x64/bin/npm --version
2022-10-22T03:37:14.7458341Z 6.14.17
2022-10-22T03:37:14.7680566Z ##[group]Run npm install axios
2022-10-22T03:37:14.7680953Z [36;1mnpm install axios[0m
2022-10-22T03:37:14.7742527Z shell: /usr/bin/bash -e {0}
2022-10-22T03:37:14.7742836Z ##[endgroup]
2022-10-22T03:37:16.2268683Z npm WARN saveError ENOENT: no such file or directory, open '/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/package.json'
2022-10-22T03:37:16.2336222Z npm notice created a lockfile as package-lock.json. You should commit this file.
2022-10-22T03:37:16.2360755Z npm WARN enoent ENOENT: no such file or directory, open '/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/package.json'
2022-10-22T03:37:16.2427600Z npm WARN GLaDOS-CheckIn No description
2022-10-22T03:37:16.2497417Z npm WARN GLaDOS-CheckIn No repository field.
2022-10-22T03:37:16.2565584Z npm WARN GLaDOS-CheckIn No README data
2022-10-22T03:37:16.2644558Z npm WARN GLaDOS-CheckIn No license field.
2022-10-22T03:37:16.2648601Z 
2022-10-22T03:37:16.2692120Z + axios@1.1.3
2022-10-22T03:37:16.2693216Z added 9 packages from 26 contributors and audited 9 packages in 0.824s
2022-10-22T03:37:16.2738832Z 
2022-10-22T03:37:16.2739356Z 1 package is looking for funding
2022-10-22T03:37:16.2739820Z   run `npm fund` for details
2022-10-22T03:37:16.2740366Z 
2022-10-22T03:37:16.2743126Z found 0 vulnerabilities
2022-10-22T03:37:16.2743462Z 
2022-10-22T03:37:16.2868410Z ##[group]Run npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
2022-10-22T03:37:16.2868994Z [36;1mnpm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth[0m
2022-10-22T03:37:16.2926331Z shell: /usr/bin/bash -e {0}
2022-10-22T03:37:16.2926621Z ##[endgroup]
2022-10-22T03:37:21.9974545Z 
2022-10-22T03:37:21.9976197Z > puppeteer@19.1.0 postinstall /home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer
2022-10-22T03:37:21.9976904Z > node install.js
2022-10-22T03:37:21.9977412Z 
2022-10-22T03:37:23.7450056Z 
2022-10-22T03:37:28.8824441Z Chromium (1045629) downloaded to /home/runner/.cache/puppeteer/chrome/linux-1045629
2022-10-22T03:37:28.9360669Z npm WARN saveError ENOENT: no such file or directory, open '/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/package.json'
2022-10-22T03:37:28.9588354Z npm WARN enoent ENOENT: no such file or directory, open '/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/package.json'
2022-10-22T03:37:28.9661907Z npm WARN GLaDOS-CheckIn No description
2022-10-22T03:37:28.9730920Z npm WARN GLaDOS-CheckIn No repository field.
2022-10-22T03:37:28.9802996Z npm WARN GLaDOS-CheckIn No README data
2022-10-22T03:37:28.9886613Z npm WARN GLaDOS-CheckIn No license field.
2022-10-22T03:37:28.9888033Z 
2022-10-22T03:37:28.9911940Z + puppeteer-extra@3.3.4
2022-10-22T03:37:28.9912713Z + puppeteer@19.1.0
2022-10-22T03:37:28.9914104Z + puppeteer-extra-plugin-stealth@2.11.1
2022-10-22T03:37:28.9917481Z added 103 packages from 113 contributors and audited 119 packages in 12.299s
2022-10-22T03:37:29.0317640Z 
2022-10-22T03:37:29.0318639Z 10 packages are looking for funding
2022-10-22T03:37:29.0319178Z   run `npm fund` for details
2022-10-22T03:37:29.0319748Z 
2022-10-22T03:37:29.0321877Z found 0 vulnerabilities
2022-10-22T03:37:29.0346350Z 
2022-10-22T03:37:29.0514196Z ##[group]Run node checkin.js
2022-10-22T03:37:29.0514632Z [36;1mnode checkin.js[0m
2022-10-22T03:37:29.0572810Z shell: /usr/bin/bash -e {0}
2022-10-22T03:37:29.0573140Z env:
2022-10-22T03:37:29.0573960Z   PUSHPLUS: ***
2022-10-22T03:37:29.0575824Z   COOKIES: ***
2022-10-22T03:37:29.0576094Z ##[endgroup]
2022-10-22T03:37:29.2901410Z Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
2022-10-22T03:37:29.2902798Z     at assert (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
2022-10-22T03:37:29.2904135Z     at ChromeLauncher.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:69:36)
2022-10-22T03:37:29.2905627Z     at PuppeteerNode.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:146:105)
2022-10-22T03:37:29.2907039Z     at PuppeteerExtra.launch (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/node_modules/puppeteer-extra/dist/index.cjs.js:128:41)
2022-10-22T03:37:29.2974027Z     at async checkInAndGetStatus (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/checkin.js:58:21)
2022-10-22T03:37:29.2974519Z     at async Promise.all (index 0)
2022-10-22T03:37:29.2975115Z     at async GLaDOSCheckIn (/home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn/checkin.js:175:27)
2022-10-22T03:37:29.3039334Z ##[group]Run gautamkrishnar/keepalive-workflow@master
2022-10-22T03:37:29.3039652Z with:
2022-10-22T03:37:29.3040033Z   gh_token: ***
2022-10-22T03:37:29.3040414Z   commit_message: Automated commit by Keepalive Workflow to keep the repository active
2022-10-22T03:37:29.3040803Z   committer_username: gkr-bot
2022-10-22T03:37:29.3041173Z   committer_email: gkr-bot@tuta.io
2022-10-22T03:37:29.3041457Z   time_elapsed: 50
2022-10-22T03:37:29.3041710Z   auto_push: true
2022-10-22T03:37:29.3041948Z ##[endgroup]
2022-10-22T03:37:29.3533877Z Nothing to do...
2022-10-22T03:37:29.3595827Z ##[group]Run Mattraks/delete-workflow-runs@v2
2022-10-22T03:37:29.3596166Z with:
2022-10-22T03:37:29.3596582Z   token: ***
2022-10-22T03:37:29.3596878Z   repository: SplitGemini/GLaDOS-CheckIn
2022-10-22T03:37:29.3597180Z   retain_days: 0
2022-10-22T03:37:29.3597440Z   keep_minimum_runs: 10
2022-10-22T03:37:29.3597732Z   delete_workflow_by_state_pattern: success
2022-10-22T03:37:29.3598067Z   baseUrl: https://api.github.com
2022-10-22T03:37:29.3598357Z ##[endgroup]
2022-10-22T03:37:29.9496295Z 💬 workflows containing state 'success' will be targeted
2022-10-22T03:37:29.9497236Z 💬 found total of 0 workflow(s)
2022-10-22T03:37:29.9600125Z Post job cleanup.
2022-10-22T03:37:30.1095528Z [command]/usr/bin/git version
2022-10-22T03:37:30.1147959Z git version 2.38.1
2022-10-22T03:37:30.1193697Z Temporarily overriding HOME='/home/runner/work/_temp/1611590f-dc81-475b-b8b4-4d18161b951d' before making global git config changes
2022-10-22T03:37:30.1194804Z Adding repository directory to the temporary git global config as a safe directory
2022-10-22T03:37:30.1199737Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/GLaDOS-CheckIn/GLaDOS-CheckIn
2022-10-22T03:37:30.1245382Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-10-22T03:37:30.1286278Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-10-22T03:37:30.1587447Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-10-22T03:37:30.1656001Z http.https://github.com/.extraheader
2022-10-22T03:37:30.1678018Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-10-22T03:37:30.1723733Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-10-22T03:37:30.2260227Z Cleaning up orphan processes

**Comment by SplitGemini** [comment]
已解决
